import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { initPlan, features, resolveFeature, selectTasks, deriveStage, WorkflowError } from '../lib/workflow.js';
const project=()=>mkdtempSync(join(tmpdir(),'dsh-specify-'));
const spec=(name='Login')=>`# Feature: ${name}\n## Problem\nx\n## Goals\nx\n## User Stories\n- US-001: x\n## Functional Requirements\n- FR-001: x\n## Success Criteria\n- SC-001: x\n## Edge Cases\n- EC-001: x\n## Out of Scope\nx\n## Assumptions\nx\n## Open Questions\nx\n`;
const plan=()=>`# Plan: Login\n## Technical Context\nx\n## Constraints from Constitution and Specification\nx\n## Architecture and Components\nx\n## Data Flow and Interfaces\nx\n## Dependencies\nx\n## Requirement Mapping\nFR-001 SC-001 EC-001\n## Testing Strategy\nx\n## Risks and Fallbacks\nx\n`;
const tasks=(checked=' ')=>`# Tasks: Login\n\n## Task List\n\n- [${checked}] T001 [FR-001] Implement login\n\n## Verification\n\nNo verification has been recorded.\n`;
test('plans initialization and enumerates deterministic features',()=>{const p=project();let x=initPlan(p);assert.equal(x.canInitialize,true);mkdirSync(join(p,'.speckit'));mkdirSync(join(p,'specs'));mkdirSync(join(p,'specs','010-z'));mkdirSync(join(p,'specs','002-a'));mkdirSync(join(p,'specs','bad'));x=features(p);assert.deepEqual(x.features.map(f=>f.name),['002-a','010-z']);assert.equal(x.nextPrefix,'011');assert.equal(x.malformed.length,1);assert.equal(resolveFeature(p,'a').feature.name,'002-a');assert.throws(()=>resolveFeature(p,'../x'),e=>e instanceof WorkflowError&&e.code==='UNSAFE_PATH');assert.throws(()=>resolveFeature(p,'other/feature'),e=>e instanceof WorkflowError&&e.code==='UNSAFE_PATH');});
test('selects tasks in document order and validates dependencies',()=>{const p=project();mkdirSync(join(p,'specs'));const file=join(p,'tasks.md');writeFileSync(file,`# Tasks: X\n## Task List\n- [x] T001 [FOUNDATION] Set up\n- [ ] T002 [FR-001] Add feature (depends: T001)\n- [ ] T003 [SC-001] Test feature (depends: T002)\n## Verification\nNo verification has been recorded.\n`);const x=selectTasks(p,file,'T003');assert.deepEqual(x.selected.map(t=>t.id),['T003']);assert.deepEqual(x.incompleteDependencies,[{task:'T003',dependency:'T002'}]);assert.throws(()=>selectTasks(p,file,''),e=>e instanceof WorkflowError&&e.code==='INVALID_SELECTION');});
test('derives stages including full verified completion',()=>{const p=project();mkdirSync(join(p,'specs'));const f=join(p,'specs','001-login');mkdirSync(f);assert.equal(deriveStage(p,'001-login').stage,'not-started');writeFileSync(join(f,'spec.md'),spec());assert.equal(deriveStage(p,'001-login').stage,'specified');writeFileSync(join(f,'plan.md'),plan());assert.equal(deriveStage(p,'001-login').stage,'planned');writeFileSync(join(f,'tasks.md'),tasks());assert.equal(deriveStage(p,'001-login').stage,'tasked');writeFileSync(join(f,'tasks.md'),tasks('x').replace('No verification has been recorded.','### Verification Run: 2026-01-01T00:00:00Z\n\n```json\n{"scope":{"kind":"full","tasks":[]},"overallResult":"pass","checks":[{"command":"npm test","exitCode":0,"result":"pass"}]}\n```'));assert.equal(deriveStage(p,'001-login').stage,'complete');});

test('rejects malformed artifact headings and identifiers',()=>{const p=project();mkdirSync(join(p,'specs'));const f=join(p,'specs','001-invalid');mkdirSync(f);writeFileSync(join(f,'plan.md'),plan());writeFileSync(join(f,'tasks.md'),tasks());writeFileSync(join(f,'spec.md'),spec().replace('## Problem','## Problematic'));assert.equal(deriveStage(p,'001-invalid').stage,'invalid');writeFileSync(join(f,'spec.md'),spec().replace('- FR-001: x','- FR-001: x\n- FR-001: duplicate'));assert.equal(deriveStage(p,'001-invalid').stage,'invalid');writeFileSync(join(f,'spec.md'),Buffer.concat([Buffer.from(spec()),Buffer.from([0xff])]));assert.equal(deriveStage(p,'001-invalid').stage,'invalid');writeFileSync(join(f,'spec.md'),spec());writeFileSync(join(f,'plan.md'),plan().replace('FR-001','FR-1'));assert.equal(deriveStage(p,'001-invalid').stage,'invalid');});

test('rejects malformed verification timestamps and scopes',()=>{const p=project();mkdirSync(join(p,'specs'));const f=join(p,'specs','001-verification');mkdirSync(f);writeFileSync(join(f,'spec.md'),spec());writeFileSync(join(f,'plan.md'),plan());const completed=`# Tasks: Login\n\n## Task List\n\n- [x] T001 [FR-001] Implement login\n- [x] T002 [SC-001] Verify login (depends: T001)\n\n## Verification\n\n`;const record=(timestamp,scope)=>`${completed}### Verification Run: ${timestamp}\n\n\`\`\`json\n${JSON.stringify({scope,overallResult:'pass',checks:[{command:'npm test',exitCode:0,result:'pass'}]})}\n\`\`\`\n`;writeFileSync(join(f,'tasks.md'),record('2026-99-99T99:99:99Z',{kind:'full',tasks:[]}));assert.equal(deriveStage(p,'001-verification').stage,'invalid');writeFileSync(join(f,'tasks.md'),record('2026-01-01T00:00:00Z',{kind:'full',tasks:[],extra:true}));assert.equal(deriveStage(p,'001-verification').stage,'invalid');writeFileSync(join(f,'tasks.md'),record('2026-01-01T00:00:00Z',{kind:'partial',tasks:['T002','T001']}));assert.equal(deriveStage(p,'001-verification').stage,'invalid');});

test('rejects symlinked task and feature paths',()=>{const p=project();mkdirSync(join(p,'specs'));const f=join(p,'specs','001-real');mkdirSync(f);writeFileSync(join(f,'tasks.md'),tasks());const taskLink=join(p,'tasks-link.md');symlinkSync(join(f,'tasks.md'),taskLink);assert.throws(()=>selectTasks(p,taskLink),e=>e instanceof WorkflowError&&e.code==='UNSAFE_PATH');const featureLink=join(p,'specs','002-link');symlinkSync(f,featureLink);assert.throws(()=>resolveFeature(p,'specs/002-link'),e=>e instanceof WorkflowError&&e.code==='UNSAFE_PATH');assert.throws(()=>deriveStage(p,featureLink),e=>e instanceof WorkflowError&&e.code==='UNSAFE_PATH');});

test('selects very large task ranges without numeric expansion',()=>{const p=project();mkdirSync(join(p,'specs'));const f=join(p,'specs','001-ranges');mkdirSync(f);const file=join(f,'tasks.md');writeFileSync(file,`# Tasks: Ranges\n## Task List\n- [ ] T001 [FR-001] First\n- [ ] T010 [FR-001] Middle\n- [ ] T999999999999999999999 [SC-001] Last\n## Verification\nNo verification has been recorded.\n`);const selected=selectTasks(p,file,'T001-T999999999999999999999');assert.deepEqual(selected.selected.map(task=>task.id),['T001','T010','T999999999999999999999']);assert.throws(()=>selectTasks(p,file,'T002-T010'),e=>e instanceof WorkflowError&&e.code==='INVALID_SELECTION');assert.throws(()=>selectTasks(p,file,'T999999999999999999999-T001'),e=>e instanceof WorkflowError&&e.code==='INVALID_SELECTION');});
