import { lstatSync, readdirSync, readFileSync, realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parseDocument } from 'yaml';
import { isSkillName } from '@deepseek-ai/dsh-skill';

const PACKAGE_ROOT = fileURLToPath(new URL('..', import.meta.url));
const SKILLS_ROOT = join(PACKAGE_ROOT, 'skills');
const allowed = new Set(['name', 'description', 'whenToUse']);
const regularDirectory = path => { try { const s=lstatSync(path); return s.isDirectory() && !s.isSymbolicLink(); } catch { return false; } };
const regularFile = path => { try { const s=lstatSync(path); return s.isFile() && !s.isSymbolicLink(); } catch { return false; } };
function diagnostic(path, code, message) { return {level:'warning',path,code,message}; }
function parseSkill(path) { let text; try { text=readFileSync(path,'utf8'); } catch(e) { throw {code:'SKILL_READ_ERROR',message:e.message}; } const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text); if(!match) throw {code:'INVALID_FRONTMATTER',message:'frontmatter must be delimited by ---'}; let doc; try { doc=parseDocument(match[1],{uniqueKeys:true}); if(doc.errors.length) throw doc.errors[0]; } catch(e) { throw {code:'INVALID_FRONTMATTER',message:`invalid YAML: ${e.message}`}; } const data=doc.toJSON(); if(!data || typeof data!=='object' || Array.isArray(data)) throw {code:'INVALID_FRONTMATTER',message:'frontmatter must be an object'}; for(const key of Object.keys(data)) if(!allowed.has(key)) throw {code:'INVALID_FRONTMATTER',message:`unknown field ${key}`}; for(const key of ['name','description']) if(typeof data[key]!=='string'||!data[key].trim()) throw {code:'INVALID_FRONTMATTER',message:`${key} must be a non-empty string`}; if(data.whenToUse !== undefined && (typeof data.whenToUse!=='string'||!data.whenToUse.trim())) throw {code:'INVALID_FRONTMATTER',message:'whenToUse must be a non-empty string'}; if(!isSkillName(data.name)) throw {code:'INVALID_FRONTMATTER',message:'name is not valid DSH kebab-case'}; return {data,content:match[2]}; }
/** Discover immediate bundled skill directories without registration or logging. */
export function discoverSkills(skillsRoot) { const skills=[], diagnostics=[], seen=new Set(); let entries; try { entries=readdirSync(skillsRoot,{withFileTypes:true}).sort((a,b)=>a.name < b.name ? -1 : a.name > b.name ? 1 : 0); } catch(e) { return {skills,diagnostics:[diagnostic(skillsRoot,'SKILL_READ_ERROR',e.message)]}; } for(const entry of entries) { const dir=join(skillsRoot,entry.name); if(!entry.isDirectory()||entry.isSymbolicLink()) continue; if(entry.name==='scripts') continue; const file=join(dir,'SKILL.md'); if(!regularFile(file)) continue; let parsed; try { parsed=parseSkill(file); } catch(e) { diagnostics.push(diagnostic(file,e.code||'INVALID_FRONTMATTER',e.message)); continue; } if(seen.has(parsed.data.name)) { diagnostics.push(diagnostic(file,'DUPLICATE_SKILL',`duplicate skill name ${parsed.data.name}`)); continue; } if(parsed.data.name!==entry.name) { diagnostics.push(diagnostic(file,'NAME_MISMATCH',`frontmatter name ${parsed.data.name} differs from directory ${entry.name}`)); continue; } seen.add(parsed.data.name); skills.push({name:parsed.data.name,description:parsed.data.description,...(parsed.data.whenToUse?{whenToUse:parsed.data.whenToUse}:{}),content:parsed.content,path:file}); } return {skills,diagnostics}; }
export const inject=['skills'];
export function apply(ctx) { const discovered=discoverSkills(SKILLS_ROOT); for(const d of discovered.diagnostics) ctx.logger?.warn?.(`dsh-specify ${d.code}: ${d.path}: ${d.message}`); return ctx.effect(()=>{ const disposers=discovered.skills.map(skill=>ctx.skills.register({...skill,source:'bundled',resourceBase:{kind:'directory',path:realpathSync(SKILLS_ROOT)},invocation:{modelInvocable:true,userInvocable:true}})); return ()=>{ for(const dispose of disposers.reverse()) dispose(); }; }); }
